[package]
name = "passcrypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
cursive = "0.20.0"
dirs = "5.0.0"
rpassword = "7.2.0"
sha2 = "0.10.6"
